/*
**  Copyright 2022 bitValence, Inc.
**  All Rights Reserved.
**
**  This program is free software; you can modify and/or redistribute it
**  under the terms of the GNU Affero General Public License
**  as published by the Free Software Foundation; version 3 with
**  attribution addendums as found in the LICENSE.txt
**
**  This program is distributed in the hope that it will be useful,
**  but WITHOUT ANY WARRANTY; without even the implied warranty of
**  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**  GNU Affero General Public License for more details.
**
**  Purpose:
**    Define the Hi_object application
**
**  Notes:
**   1. This file was automatically generated by cFS Basecamp's app
**      creation tool. If you edit it, your changes will be lost if
**      a new app with the same name is created. 
**
*/

#ifndef _hi_object_app_
#define _hi_object_app_

/*
** Includes
*/

#include "app_cfg.h"
#include "exobj.h"

/***********************/
/** Macro Definitions **/
/***********************/

/*
** Events
*/

#define HI_OBJECT_INIT_APP_EID    (HI_OBJECT_BASE_EID + 0)
#define HI_OBJECT_NOOP_EID        (HI_OBJECT_BASE_EID + 1)
#define HI_OBJECT_EXIT_EID        (HI_OBJECT_BASE_EID + 2)
#define HI_OBJECT_INVALID_MID_EID (HI_OBJECT_BASE_EID + 3)


/**********************/
/** Type Definitions **/
/**********************/


/******************************************************************************
** Command Packets
** - See EDS command definitions in hi_object.xml
*/


/******************************************************************************
** Telmetery Packets
** - See EDS command definitions in hi_object.xml
*/


/******************************************************************************
** HI_OBJECT_Class
*/
typedef struct
{

   /* 
   ** App Framework
   */ 
    
   INITBL_Class_t  IniTbl; 
   CMDMGR_Class_t  CmdMgr;
   
   /*
   ** Command Packets
   */

 
   /*
   ** Telemetry Packets
   */
   
   HI_OBJECT_StatusTlm_t  StatusTlm;
   
   /*
   ** HI_OBJECT State & Contained Objects
   */ 
           
   uint32           PerfId;
   CFE_SB_PipeId_t  CmdPipe;
   CFE_SB_MsgId_t   CmdMid;
   CFE_SB_MsgId_t   ExecuteMid;
   CFE_SB_MsgId_t   SendStatusMid;

   EXOBJ_Class_t  ExObj;
   
} HI_OBJECT_Class_t;


/*******************/
/** Exported Data **/
/*******************/

extern HI_OBJECT_Class_t  Hi_object;


/************************/
/** Exported Functions **/
/************************/


/******************************************************************************
** Function: HI_OBJECT_AppMain
**
*/
void HI_OBJECT_AppMain(void);


/******************************************************************************
** Function: HI_OBJECT_NoOpCmd
**
*/
bool HI_OBJECT_NoOpCmd(void *ObjDataPtr, const CFE_MSG_Message_t *MsgPtr);


/******************************************************************************
** Function: HI_OBJECT_ResetAppCmd
**
*/
bool HI_OBJECT_ResetAppCmd(void *ObjDataPtr, const CFE_MSG_Message_t *MsgPtr);


#endif /* _hi_object_ */
